from .catalog_page_locators import CatalogPageLocators
from .header_locators import HeaderLocators
from .login_page_locators import LoginPageLocators
from .main_page_locators import MainPageLocators
from .product_card_page_locators import ProductCardPageLocators
from .registration_page_locators import RegistrationPageLocators
from .registration_success_page_locators import RegistrationSuccessPageLocators
