from .header_locators import HeaderLocators
from .main_page_locators import MainPageLocators
from .registration_page_locators import RegistrationPageLocators
from .registration_success_page_locators import RegistrationSuccessPageLocators
