from .cart_page import CartPage
from .catalog_page import CatalogPage
from .checkout_as_guest_page import CheckoutAsGuestPage
from .checkout_completed_page import CheckoutCompletedPage
from .checkout_page import CheckoutPage
from .header import Header
from .login_page import LoginPage
from .main_page import MainPage
from .product_card_page import ProductCardPage
from .registration_page import RegistrationPage
from .registration_success_page import RegistrationSuccessPage
from .wishlist_page import WishlistPage
