name: Run tests and generate allure report

on:
  workflow_dispatch

jobs:
  autotests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install allure
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop install allure

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir allure-results -n 4

      - name: Generate allure report
        run: ~\scoop\apps\allure\2.20.1\bin\allure.bat generate allure-results
        if: always()

      - name: Push allure report to branch gh-pages
        run: |
          git config --global user.email "popovpn7@gmail.com"
          git config --global user.name "Petr Popov"
          git fetch
          git checkout gh-pages
          git add allure-report/
          git commit -m "Add allure-report"
          git push